server:
  port: ${CONTAINER_PORT:8080}
spring:
  application:
    name: @project.artifactId@
  cloud:
    gateway:
      routes:
        - id: reward
          uri: ${gateway.url.reward}
          predicates:
            - Path=/api/reward/**
  profiles:
    active: ${ACTIVE_ENVIRONMENT:local}
gateway:
  url:
    reward: http://reward.${SERVICE_DISCOVERY_NAMESPACE_NAME}
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    io.netty.resolver.dns: DEBUG